import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import Anthropic from '@anthropic-ai/sdk';
import OpenAI from 'openai';
import sharp from 'sharp';
import Tesseract from 'tesseract.js';
import * as FormData from 'form-data';

dotenv.config();

interface ImageAnalysisResult {
  text?: string;
    objects?: string[];
      analysis?: string;
        confidence?: number;
          metadata?: Record<string, any>;
          }

          class ImageMCPServer {
            private claudeClient: Anthropic;
              private openaiClient: OpenAI;

                constructo
                    this.claudeClient = new Anthropic({
                          apiKey: process.env.CLAUDE_API_KEY,
                              });
                                  this.openaiClient = new OpenAI({
                                        apiKey: process.env.CHATGPT_API_KEY,
                                            });
                                              }

                                                // Bildverarbeitung - Resize und Format konvertieren
                                                  async processImage(imagePath: string, maxSizeMB: number = 50): Promise<Buffer> {
                                                      try {
                                                            const imageBuffer = fs.readFileSync(imagePath);

                                                                        if (imageBuffer.length > maxSizeMB * 1024 * 1024) {
                                                                                return await sharp(imageBuffer)
                                                                                          .resize(1024, 1024, {
                                                                                                      fit: 'inside',
                                                                                                                  withoutEnlargement: true,
                                                                                                                            })
                                                                                                                                      .jpeg({ quality: 80 })
                                                                                                                                                .toBuffer();
                                                                                                                                                      }
                                                                                                                                                            return imageBuffer;
                                                                                                                                                                } catch (error) {
                                                                                                                                                                      throw new Error(`Image processing failed: ${error}`);
                                                                                                                                                                          }
                                                                                                                                                                            }
                                                                                                                                                                            
                                                                                                                                                                              // OCR - Text aus Bildern extrahieren
                                                                                                                                                                                async extractTextWithOCR(imagePath: string): Promise<string> {
                                                                                                                                                                                    try {
                                                                                                                                                                                          const { data: { text } } = await Tesseract.recognize(
                                                                                                                                                                                                  imagePath,
                                                                                                                                                                                                          process.env.OCR_LANGUAGE || 'eng'
                                                                                                                                                                                                                );
                                                                                                                                                                                                                      return text;
                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                throw new Error(`OCR extraction failed: ${error}`);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                        // Bildanalyse mit Claude
                                                                                                                                                                                                                                          async analyzeImageWithClaude(imagePath: string): Promise<string> {
                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                    const imageBuffer = await this.processImage(imagePath);
                                                                                                                                                                                                                                                          const base64Image = imageBuffer.toString('base64');
                                                                                                                                                                                                                                                                const imageExt = path.extname(imagePath).toLowerCase().replace('.', '');
                                                                                                                                                                                                                                                                      const mediaType = this.getMediaType(imageExt);
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                            const response = await this.claudeClient.messages.create({
                                                                                                                                                                                                                                                                                    model: 'claude-3-5-sonnet-20241022',
                                                                                                                                                                                                                                                                                            max_tokens: 1024,
                                                                                                                                                                                                                                                                                                    messages: [
                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                          role: 'user',
                                                                                                                                                                                                                                                                                                                                      content: [
                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                    type: 'image',
                                                                                                                                                                                                                                                                                                                                                                                    source: {
                                                                                                                                                                                                                                                                                                                                                                                                      type: 'base64',
                                                                                                                                                                                                                                                                                                                                                                                                                        media_type: mediaType as 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp',
                                                                                                                                                                                                                                                                                                                                                                                                                                          data: base64Image,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type: 'text',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      text: 'Analyze this image in detail. Describe: 1) What you see, 2) Objects detected, 3) Text visible, 4) Overall context.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return response.content[0].type === 'text' ? response.content[0].text : '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        throw new Error(`Claude image analysis failed: ${error}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Bildanalyse mit ChatGPT Vision
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async analyzeImageWithChatGPT(imagePath: string): Promise<string> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const imageBuffer = await this.processImage(imagePath);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const base64Image = imageBuffer.toString('base64');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const imageExt = path.extname(imagePath).toLowerCase().replace('.', '');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const mediaType = this.getMediaType(imageExt);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const response = await this.openaiClient.chat.completions.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            model: process.env.CHATGPT_MODEL || 'gpt-4-vision',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    max_tokens: 1024,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            messages: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  role: 'user',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              content: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type: 'image_url',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            image_url: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              url: `data:${mediaType};base64,${base64Image}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type: 'text',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text: 'Analyze this image in detail. Describe: 1) What you see, 2) Objects detected, 3) Text visible, 4) Overall context.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return response.choices[0].message.content || '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Error(`ChatGPT image analysis failed: ${error}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Kombinierte Bildanalyse (Claude + ChatGPT)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      async analyzeImageComprehensive(imagePath: string): Promise<ImageAnalysisResult> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const [claudeAnalysis, chatgptAnalysis, ocrText] = await Promise.all([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.analyzeImageWithClaude(imagePath),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.analyzeImageWithChatGPT(imagePath),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.extractTextWithOCR(imagePath),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text: ocrText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    analysis: `Claude: ${claudeAnalysis}\n\nChatGPT: ${chatgptAnalysis}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            metadata: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      processedAt: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                filePath: imagePath,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        throw new Error(`Comprehensive analysis failed: ${error}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private getMediaType(ext: string): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const mediaTypes: Record<string, string> = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          jpg: 'image/jpeg',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                jpeg: 'image/jpeg',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      png: 'image/png',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gif: 'image/gif',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  webp: 'image/webp',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return mediaTypes[ext.toLowerCase()] || 'image/jpeg';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Export server
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default ImageMCPServer;
